### ISSUE TITLE
Can't import report json into diff viewer anymore

### ISSUE THREAD

**Issue by DLeich** [voxpupuli/puppet-catalog_diff#57]
It looks like commit 16730d65acb795805310dfb340b4fea1403ecbee introduced a regression.  The json output no longer includes the overview data for all nodes, which is a requirement for the diff viewer to work.  Specifically, the diff viewer tool looks for `most_differences` here:
https://github.com/camptocamp/puppet-catalog-diff-viewer/blob/master/catalog_viewer.js#L161

But with the latest commit of this module, that field is no longer present in the output reports that I've generated.  I get the following error in my browser developer tools:
`Uncaught TypeError: Cannot read properties of undefined (reading 'length')` `catalog_viewer.js:161`

Reverting to the commit prior to PR-50 brings back a valid report json again.

**Comment by JoshuaSmeda** [comment]
I have run into the same issue. Would be great if the PR can be reviewed!
