### ISSUE TITLE
Reporting for 'failed_nodes' doesn't work

### ISSUE THREAD

**Issue by JoshuaSmeda** [voxpupuli/puppet-catalog_diff#92]
If you use Catalog Diff Viewer, you might notice that there is a `failed` selector on custom reports (reports that are generated from Catalog Diff):

![Screenshot 2022-11-07 at 15 43 35](https://user-images.githubusercontent.com/39983886/200325248-c76d3803-6080-43e1-a926-9d6a61dcf2ec.png)

[The catalog diff face doesn't compute and write the `failed_nodes` and their tallies to the report file](https://github.com/voxpupuli/puppet-catalog_diff/blob/master/lib/puppet/face/catalog/diff.rb#L255) (anymore?)

The default report that gets put down, has `failed_nodes` set and presents correctly on the front end. You can find an example here: [Catalog Diff Viewer Demo Report](https://raw.githubusercontent.com/voxpupuli/puppet-catalog-diff-viewer/master/data/demo1.json)

I would like the `failed_nodes` functionality to be implemented so that I'm able to fully utilize the front end (Viewer) as intended without relying on the stdout of the Catalog Diff to know if there is an error.

**Comment by vchepkov** [comment]
I noticed the same issue. File created using output_report argument doesn't include pull_output :
```
  "pull_output": {
    "failed_nodes": {
  ...
```
